[package]
name = "notugly"
version = "0.2.2"
edition = "2021"
authors = ["martin-fl"]
description = "A simple and generic pretty-printing library"
readme = "README.md"
license = "MIT"
repository = "https://github.com/martin-fl/notugly"
documentation = "https://docs.rs/notugly/"